apiVersion: 1

datasources:
  - name: InfluxDB_v2_Flux
    type: influxdb
    access: proxy
    url: http://sprc_influx:8086
    secureJsonData:
      token: $INFLUX_TOKEN
    jsonData:
      version: Flux
      organization: $INFLUX_ORG
      defaultBucket: $INFLUX_BUCKET
      tlsSkipVerify: true

